export const OUTFIT_FRAME_WIDTH = 96;
export const OUTFIT_FRAME_HEIGHT = 144;
export const OUTFIT_SHEET_COLUMNS = 4;
export const OUTFIT_SHEET_ROWS = 4;
export const OUTFIT_SHEET_WIDTH = OUTFIT_FRAME_WIDTH * OUTFIT_SHEET_COLUMNS;
export const OUTFIT_SHEET_HEIGHT = OUTFIT_FRAME_HEIGHT * OUTFIT_SHEET_ROWS;
export const OUTFIT_WORLD_SCALE = 0.5;
