export const GAME_ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  REALM_UNAVAILABLE: 'REALM_UNAVAILABLE',
  CHARACTER_REQUIRED: 'CHARACTER_REQUIRED',
  CHARACTER_ALREADY_EXISTS: 'CHARACTER_ALREADY_EXISTS',
  CHARACTER_NAME_TAKEN: 'CHARACTER_NAME_TAKEN',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  SESSION_NOT_READY: 'SESSION_NOT_READY',
  MOVE_TOO_FAST: 'MOVE_TOO_FAST',
  MOVE_OUT_OF_BOUNDS: 'MOVE_OUT_OF_BOUNDS',
  MOVE_COLLISION: 'MOVE_COLLISION',
  MOVE_TILE_OCCUPIED: 'MOVE_TILE_OCCUPIED',
  MOVE_NO_PATH: 'MOVE_NO_PATH',
  MOVE_PATH_TOO_LONG: 'MOVE_PATH_TOO_LONG',
  MOVE_PATH_SEARCH_LIMIT: 'MOVE_PATH_SEARCH_LIMIT',
  MAP_INVALID: 'MAP_INVALID',
  PORTAL_INVALID: 'PORTAL_INVALID',
  INVENTORY_FULL: 'INVENTORY_FULL',
  INSUFFICIENT_SILVER: 'INSUFFICIENT_SILVER',
  ITEM_NOT_SELLABLE: 'ITEM_NOT_SELLABLE',
  ITEM_EQUIPPED: 'ITEM_EQUIPPED',
  ITEM_EFFECT_NOT_NEEDED: 'ITEM_EFFECT_NOT_NEEDED',
  MERCHANT_NOT_AVAILABLE: 'MERCHANT_NOT_AVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type GameErrorCode = (typeof GAME_ERROR_CODES)[keyof typeof GAME_ERROR_CODES];

export class GameError extends Error {
  constructor(
    public readonly code: GameErrorCode,
    public readonly messageKey: string,
    public readonly details?: Record<string, unknown>,
  ) {
    super(code);
    this.name = 'GameError';
  }
}
