ALTER TYPE "SkillTargeting" ADD VALUE IF NOT EXISTS 'ALLY';
ALTER TYPE "SkillTargeting" ADD VALUE IF NOT EXISTS 'ALL_ALLIES';
ALTER TYPE "SkillTargeting" ADD VALUE IF NOT EXISTS 'ALL_ENEMIES';
ALTER TYPE "SkillTargeting" ADD VALUE IF NOT EXISTS 'FRONT_ROW';
ALTER TYPE "SkillTargeting" ADD VALUE IF NOT EXISTS 'BACK_ROW';
ALTER TYPE "SkillTargeting" ADD VALUE IF NOT EXISTS 'ADJACENT';
