import type { PvpModeDefinition, PvpModeKey } from './pvp.types.js';

const MODES: Readonly<Record<PvpModeKey, PvpModeDefinition>> = {
  DUEL_1V1: {
    key: 'DUEL_1V1',
    version: 1,
    engagementKind: 'DUEL',
    objective: 'ELIMINATION',
    teamSize: 1,
    minTeamSize: 1,
    maxRounds: 1,
    timeLimitMs: 8 * 60_000,
    scoreToWin: 1,
    tieBreaker: 'TOTAL_HP_PERCENT',
    disconnectPolicy: 'GRACE_THEN_FORFEIT',
    rewardProfile: 'DUEL',
    ratingPool: 'duel-1v1',
    normalized: false,
    allowedConsumableKeys: [],
  },
  SKIRMISH_2V2: {
    key: 'SKIRMISH_2V2',
    version: 1,
    engagementKind: 'RANKED',
    objective: 'ELIMINATION',
    teamSize: 2,
    minTeamSize: 2,
    maxRounds: 3,
    timeLimitMs: 12 * 60_000,
    scoreToWin: 2,
    tieBreaker: 'TOTAL_HP_PERCENT',
    disconnectPolicy: 'GRACE_THEN_FORFEIT',
    rewardProfile: 'RANKED_SMALL',
    ratingPool: 'ranked-2v2',
    normalized: true,
    allowedConsumableKeys: ['minor-healing-tonic'],
  },
  SKIRMISH_3V3: {
    key: 'SKIRMISH_3V3',
    version: 1,
    engagementKind: 'RANKED',
    objective: 'ELIMINATION',
    teamSize: 3,
    minTeamSize: 3,
    maxRounds: 3,
    timeLimitMs: 15 * 60_000,
    scoreToWin: 2,
    tieBreaker: 'SURVIVORS',
    disconnectPolicy: 'GRACE_THEN_FORFEIT',
    rewardProfile: 'RANKED_SMALL',
    ratingPool: 'ranked-3v3',
    normalized: true,
    allowedConsumableKeys: ['minor-healing-tonic'],
  },
  WARPARTY_5V5: {
    key: 'WARPARTY_5V5',
    version: 1,
    engagementKind: 'RANKED',
    objective: 'ELIMINATION',
    teamSize: 5,
    minTeamSize: 5,
    maxRounds: 1,
    timeLimitMs: 20 * 60_000,
    scoreToWin: 1,
    tieBreaker: 'SURVIVORS',
    disconnectPolicy: 'GRACE_THEN_FORFEIT',
    rewardProfile: 'RANKED_LARGE',
    ratingPool: 'ranked-5v5',
    normalized: true,
    allowedConsumableKeys: ['minor-healing-tonic'],
  },
  WARHOST_10V10: {
    key: 'WARHOST_10V10',
    version: 1,
    engagementKind: 'RANKED',
    objective: 'ELIMINATION',
    teamSize: 10,
    minTeamSize: 10,
    maxRounds: 1,
    timeLimitMs: 25 * 60_000,
    scoreToWin: 1,
    tieBreaker: 'SURVIVORS',
    disconnectPolicy: 'FORFEIT_ACTOR',
    rewardProfile: 'RANKED_LARGE',
    ratingPool: 'ranked-10v10',
    normalized: true,
    allowedConsumableKeys: ['minor-healing-tonic'],
  },
  CONTROL_RITUAL_5V5: {
    key: 'CONTROL_RITUAL_5V5',
    version: 1,
    engagementKind: 'OBJECTIVE',
    objective: 'CONTROL_RITUAL',
    teamSize: 5,
    minTeamSize: 5,
    maxRounds: 1,
    timeLimitMs: 18 * 60_000,
    scoreToWin: 100,
    tieBreaker: 'OBJECTIVE_SCORE',
    disconnectPolicy: 'GRACE_THEN_FORFEIT',
    rewardProfile: 'RANKED_LARGE',
    ratingPool: 'objective-control-5v5',
    normalized: true,
    allowedConsumableKeys: ['minor-healing-tonic'],
  },
  RELIC_HOLD_10V10: {
    key: 'RELIC_HOLD_10V10',
    version: 1,
    engagementKind: 'OBJECTIVE',
    objective: 'RELIC_HOLD',
    teamSize: 10,
    minTeamSize: 10,
    maxRounds: 1,
    timeLimitMs: 22 * 60_000,
    scoreToWin: 150,
    tieBreaker: 'OBJECTIVE_SCORE',
    disconnectPolicy: 'FORFEIT_ACTOR',
    rewardProfile: 'RANKED_LARGE',
    ratingPool: 'objective-relic-10v10',
    normalized: true,
    allowedConsumableKeys: ['minor-healing-tonic'],
  },
};

export function listPvpModes(): readonly PvpModeDefinition[] {
  return Object.values(MODES);
}

export function getPvpModeDefinition(key: PvpModeKey): PvpModeDefinition {
  return MODES[key];
}
