import type { EncounterDefinition } from './encounter.types.js';

const broodHunt: EncounterDefinition = {
  key: 'brood-hunt',
  version: 1,
  name: 'Polowanie Pomiotu',
  difficulty: 'BASE',
  ranks: ['SPAWN'],
  recommendedPartySize: 3,
  minimumPartySize: 1,
  maximumPartySize: 10,
  actors: [
    {
      key: 'brood-alpha',
      name: 'Alfa Pomiotu',
      role: 'LEADER',
      characterClass: 'ARCHER',
      formation: 'FRONT',
      levelOffset: 0,
      statScale: 1,
      skillKeys: ['archer-quick-shot', 'archer-snare-trap'],
      ai: {
        role: 'LEADER',
        targetPolicy: 'LOWEST_HP',
        actionWeights: { SKILL: 4, BASIC_ATTACK: 3, MARK: 1, DEFEND: 1 },
        phaseActionPriority: { desperation: ['MARK', 'SKILL', 'BASIC_ATTACK'] },
      },
    },
    {
      key: 'brood-guard',
      name: 'Tarczownik Pomiotu',
      role: 'FRONTLINER',
      characterClass: 'WARRIOR',
      formation: 'FRONT',
      levelOffset: 0,
      statScale: 0.82,
      skillKeys: ['warrior-shield-bash', 'warrior-iron-guard'],
      ai: {
        role: 'FRONTLINER',
        targetPolicy: 'FRONT_LINE',
        actionWeights: { INTERCEPT: 5, DEFEND: 3, SKILL: 3, BASIC_ATTACK: 2 },
      },
    },
    {
      key: 'brood-spitter',
      name: 'Jadowity Pluj',
      role: 'EXECUTIONER',
      characterClass: 'ARCHER',
      formation: 'BACK',
      levelOffset: 1,
      statScale: 0.72,
      skillKeys: ['archer-quick-shot', 'archer-piercing-arrow'],
      ai: {
        role: 'EXECUTIONER',
        targetPolicy: 'BACK_LINE',
        actionWeights: { SKILL: 5, BASIC_ATTACK: 2, MARK: 2, REPOSITION: 1 },
      },
    },
    {
      key: 'brood-mender',
      name: 'Tkacz Pomiotu',
      role: 'SUPPORT',
      characterClass: 'MAGE',
      formation: 'BACK',
      levelOffset: 1,
      statScale: 0.65,
      skillKeys: ['mage-arcane-spark', 'mage-frost-nova'],
      ai: {
        role: 'SUPPORT',
        targetPolicy: 'PROTECT_LEADER',
        actionWeights: { CLEANSE: 5, TRANSFER_ENERGY: 4, MARK: 3, SKILL: 2, DEFEND: 1 },
      },
    },
    ...['a', 'b', 'c'].map((suffix, index) => ({
      key: `broodling-${suffix}`,
      name: `Pomiotnik ${index + 1}`,
      role: 'SUMMON' as const,
      characterClass: 'ARCHER' as const,
      formation: index % 2 === 0 ? ('FRONT' as const) : ('BACK' as const),
      levelOffset: -1,
      statScale: 0.45,
      skillKeys: ['archer-quick-shot'],
      ai: {
        role: 'SUMMON' as const,
        targetPolicy: 'RANDOM_LEGAL' as const,
        actionWeights: { BASIC_ATTACK: 4, SKILL: 2, DEFEND: 1 },
      },
    })),
  ],
  initialActorKeys: ['brood-alpha'],
  scaling: [
    {
      minPartySize: 1,
      actorKeys: ['brood-alpha'],
      healthMultiplier: 1,
      powerMultiplier: 0.9,
      rewardMultiplier: 1,
      telegraphTargetCount: 1,
      breakCapacity: 1,
      targetTurns: 7,
      mechanics: ['ALPHA_HUNT'],
    },
    {
      minPartySize: 3,
      actorKeys: ['brood-alpha', 'brood-guard'],
      healthMultiplier: 1.25,
      powerMultiplier: 1,
      rewardMultiplier: 1.4,
      telegraphTargetCount: 1,
      breakCapacity: 2,
      targetTurns: 9,
      mechanics: ['ALPHA_HUNT', 'FRONT_GUARD', 'SINGLE_SUMMON'],
    },
    {
      minPartySize: 5,
      actorKeys: ['brood-alpha', 'brood-guard', 'brood-spitter'],
      healthMultiplier: 1.55,
      powerMultiplier: 1.08,
      rewardMultiplier: 1.9,
      telegraphTargetCount: 2,
      breakCapacity: 3,
      targetTurns: 11,
      mechanics: ['ALPHA_HUNT', 'FRONT_GUARD', 'BACKLINE_PRESSURE', 'DOUBLE_SUMMON'],
    },
    {
      minPartySize: 10,
      actorKeys: ['brood-alpha', 'brood-guard', 'brood-spitter', 'brood-mender'],
      healthMultiplier: 2.05,
      powerMultiplier: 1.18,
      rewardMultiplier: 3,
      telegraphTargetCount: 3,
      breakCapacity: 5,
      targetTurns: 14,
      mechanics: [
        'ALPHA_HUNT',
        'FRONT_GUARD',
        'BACKLINE_PRESSURE',
        'SUPPORT_CLEANSE',
        'TRIPLE_SUMMON',
      ],
    },
  ],
  phases: [
    { key: 'stalk', label: 'Obława', conditions: [], mechanics: ['ALPHA_HUNT'] },
    {
      key: 'swarm',
      label: 'Rój',
      conditions: [{ type: 'ENEMY_HP_AT_MOST', ratio: 0.7 }],
      mechanics: ['SUMMON_WAVE', 'FRONT_GUARD'],
      summonActorKeys: ['broodling-a', 'broodling-b'],
      arenaModifier: 'NEST_MIASMA',
    },
    {
      key: 'desperation',
      label: 'Szał gniazda',
      conditions: [
        { type: 'ACTOR_HP_AT_MOST', actorKey: 'brood-alpha', ratio: 0.35 },
        { type: 'TURN_AT_LEAST', turn: 12 },
      ],
      mechanics: ['FOCUS_MARKED_TARGET', 'FINAL_SUMMON'],
      summonActorKeys: ['broodling-c'],
      arenaModifier: 'COLLAPSING_NEST',
    },
  ],
  telegraphs: [],
  summonLimit: 3,
  reward: { minimumActiveTurnRatio: 0.2, minimumContribution: 1, lateJoinCutoff: 0.7 },
  victory: { type: 'DEFEAT_ALL' },
  defeat: { type: 'PLAYERS_DEFEATED' },
};

const executionCircle: EncounterDefinition = {
  key: 'execution-circle',
  version: 1,
  name: 'Krąg Kata',
  difficulty: 'CHALLENGING',
  ranks: ['EXECUTIONER', 'ARCH_EXECUTIONER', 'REAPER', 'ANCIENT'],
  recommendedPartySize: 5,
  minimumPartySize: 1,
  maximumPartySize: 10,
  actors: [
    {
      key: 'executioner',
      name: 'Mistrz Egzekucji',
      role: 'LEADER',
      characterClass: 'WARRIOR',
      formation: 'FRONT',
      levelOffset: 0,
      statScale: 1,
      skillKeys: ['warrior-shield-bash', 'warrior-cleave', 'warrior-iron-guard'],
      ai: {
        role: 'LEADER',
        targetPolicy: 'MARKED_OR_EXPOSED',
        actionWeights: { SKILL: 5, MARK: 3, BASIC_ATTACK: 2, DEFEND: 1 },
        phaseActionPriority: { execution: ['MARK', 'SKILL', 'BASIC_ATTACK'] },
      },
    },
    {
      key: 'chain-guard',
      name: 'Strażnik Łańcucha',
      role: 'FRONTLINER',
      characterClass: 'WARRIOR',
      formation: 'FRONT',
      levelOffset: 0,
      statScale: 0.9,
      skillKeys: ['warrior-shield-bash', 'warrior-iron-guard'],
      ai: {
        role: 'FRONTLINER',
        targetPolicy: 'PROTECT_LEADER',
        actionWeights: { INTERCEPT: 6, DEFEND: 4, SKILL: 3, BASIC_ATTACK: 2 },
      },
    },
    {
      key: 'blood-scribe',
      name: 'Skryba Krwi',
      role: 'SUPPORT',
      characterClass: 'MAGE',
      formation: 'BACK',
      levelOffset: 1,
      statScale: 0.78,
      skillKeys: ['mage-arcane-spark', 'mage-frost-nova', 'mage-meteor'],
      ai: {
        role: 'SUPPORT',
        targetPolicy: 'LOWEST_RESOURCE',
        actionWeights: { CLEANSE: 5, TRANSFER_ENERGY: 4, SKILL: 4, MARK: 2, DEFEND: 1 },
        phaseActionPriority: { blood_rite: ['SKILL', 'MARK'], execution: ['SKILL', 'TRANSFER_ENERGY'] },
      },
    },
    {
      key: 'harrier',
      name: 'Łowca Skazańców',
      role: 'EXECUTIONER',
      characterClass: 'ARCHER',
      formation: 'BACK',
      levelOffset: 1,
      statScale: 0.8,
      skillKeys: ['archer-piercing-arrow', 'archer-snare-trap', 'archer-rain-of-arrows'],
      ai: {
        role: 'EXECUTIONER',
        targetPolicy: 'BACK_LINE',
        actionWeights: { SKILL: 6, MARK: 3, BASIC_ATTACK: 2, REPOSITION: 1 },
      },
    },
    {
      key: 'ritual-blade',
      name: 'Ostrze Rytuału',
      role: 'EXECUTIONER',
      characterClass: 'WARRIOR',
      formation: 'FRONT',
      levelOffset: 2,
      statScale: 0.84,
      skillKeys: ['warrior-cleave', 'warrior-battle-cry'],
      ai: {
        role: 'EXECUTIONER',
        targetPolicy: 'HIGHEST_HP',
        actionWeights: { SKILL: 5, BASIC_ATTACK: 3, TAUNT: 2, DEFEND: 1 },
      },
    },
    {
      key: 'ritual-warden',
      name: 'Strażnik Rytuału',
      role: 'FRONTLINER',
      characterClass: 'WARRIOR',
      formation: 'FRONT',
      levelOffset: 2,
      statScale: 0.82,
      skillKeys: ['warrior-shield-bash', 'warrior-iron-guard'],
      ai: {
        role: 'FRONTLINER',
        targetPolicy: 'PROTECT_LEADER',
        actionWeights: { INTERCEPT: 6, DEFEND: 4, TAUNT: 3, SKILL: 2 },
      },
    },
    {
      key: 'hex-chanter',
      name: 'Kantor Klątwy',
      role: 'SUPPORT',
      characterClass: 'MAGE',
      formation: 'BACK',
      levelOffset: 2,
      statScale: 0.74,
      skillKeys: ['mage-arcane-spark', 'mage-frost-nova'],
      ai: {
        role: 'SUPPORT',
        targetPolicy: 'LOWEST_RESOURCE',
        actionWeights: { CLEANSE: 5, TRANSFER_ENERGY: 4, MARK: 3, SKILL: 2, DEFEND: 1 },
      },
    },
    ...['a', 'b', 'c'].map((suffix, index) => ({
      key: `bound-shade-${suffix}`,
      name: `Spętany Cień ${index + 1}`,
      role: 'SUMMON' as const,
      characterClass: index === 1 ? ('MAGE' as const) : ('ARCHER' as const),
      formation: index === 0 ? ('FRONT' as const) : ('BACK' as const),
      levelOffset: -1,
      statScale: 0.55,
      skillKeys: index === 1 ? ['mage-arcane-spark'] : ['archer-quick-shot'],
      ai: {
        role: 'SUMMON' as const,
        targetPolicy: 'LOWEST_HP' as const,
        actionWeights: { SKILL: 3, BASIC_ATTACK: 3, DEFEND: 1 },
      },
    })),
  ],
  initialActorKeys: ['executioner'],
  scaling: [
    {
      minPartySize: 1,
      actorKeys: ['executioner'],
      healthMultiplier: 1,
      powerMultiplier: 0.88,
      rewardMultiplier: 1,
      telegraphTargetCount: 1,
      breakCapacity: 1,
      targetTurns: 8,
      mechanics: ['VERDICT_MARK'],
    },
    {
      minPartySize: 3,
      actorKeys: ['executioner', 'chain-guard'],
      healthMultiplier: 1.35,
      powerMultiplier: 1,
      rewardMultiplier: 1.55,
      telegraphTargetCount: 1,
      breakCapacity: 2,
      targetTurns: 10,
      mechanics: ['VERDICT_MARK', 'LEADER_INTERCEPT', 'SINGLE_SHADE'],
    },
    {
      minPartySize: 5,
      actorKeys: ['executioner', 'chain-guard', 'blood-scribe'],
      healthMultiplier: 1.72,
      powerMultiplier: 1.1,
      rewardMultiplier: 2.2,
      telegraphTargetCount: 2,
      breakCapacity: 3,
      targetTurns: 12,
      mechanics: ['VERDICT_MARK', 'LEADER_INTERCEPT', 'METEOR_TELEGRAPH', 'DOUBLE_SHADE'],
    },
    {
      minPartySize: 10,
      actorKeys: [
        'executioner',
        'chain-guard',
        'blood-scribe',
        'harrier',
        'ritual-blade',
        'ritual-warden',
        'hex-chanter',
      ],
      healthMultiplier: 2.05,
      powerMultiplier: 1.18,
      rewardMultiplier: 3.6,
      telegraphTargetCount: 4,
      breakCapacity: 5,
      targetTurns: 14,
      mechanics: [
        'VERDICT_MARK',
        'LEADER_INTERCEPT',
        'METEOR_TELEGRAPH',
        'BACKLINE_HUNT',
        'PARALLEL_SUPPORT',
        'TRIPLE_SHADE',
      ],
    },
  ],
  phases: [
    { key: 'verdict', label: 'Wyrok', conditions: [], mechanics: ['VERDICT_MARK'] },
    {
      key: 'blood_rite',
      label: 'Rytuał krwi',
      conditions: [{ type: 'ENEMY_HP_AT_MOST', ratio: 0.65 }],
      mechanics: ['METEOR_TELEGRAPH', 'SUMMON_SHADE'],
      summonActorKeys: ['bound-shade-a', 'bound-shade-b'],
      arenaModifier: 'BLOOD_SIGILS',
    },
    {
      key: 'execution',
      label: 'Egzekucja',
      conditions: [
        { type: 'ACTOR_HP_AT_MOST', actorKey: 'executioner', ratio: 0.3 },
        { type: 'TURN_AT_LEAST', turn: 14 },
      ],
      mechanics: ['FOCUS_EXPOSED', 'FINAL_SHADE', 'ENRAGE'],
      summonActorKeys: ['bound-shade-c'],
      arenaModifier: 'CLOSING_CIRCLE',
    },
  ],
  telegraphs: [{ skillKey: 'mage-meteor', counters: ['DEFEND', 'INTERRUPT', 'INTERCEPT'] }],
  summonLimit: 3,
  reward: { minimumActiveTurnRatio: 0.25, minimumContribution: 2, lateJoinCutoff: 0.65 },
  victory: { type: 'DEFEAT_ALL' },
  defeat: { type: 'PLAYERS_DEFEATED' },
};

export const ENCOUNTER_CATALOG = [broodHunt, executionCircle] as const;

export function selectLatestEncounterForRank(
  definitions: readonly EncounterDefinition[],
  rank: EncounterDefinition['ranks'][number],
): EncounterDefinition {
  const encounter = definitions
    .filter((candidate) => candidate.ranks.includes(rank))
    .sort((left, right) => right.version - left.version)[0];
  if (!encounter) throw new Error(`Missing encounter definition for mob rank ${rank}.`);
  return encounter;
}

export function encounterForRank(rank: EncounterDefinition['ranks'][number]): EncounterDefinition {
  return selectLatestEncounterForRank(ENCOUNTER_CATALOG, rank);
}
