import type {
  ItemAffixDefinition,
  ItemCurseDefinition,
  ItemRecipeDefinition,
  ItemRelicEffectDefinition,
  ItemSalvageProfile,
} from './itemization.types.js';

export const ITEM_AFFIX_POOLS: Readonly<Record<string, readonly ItemAffixDefinition[]>> = {
  'martial-main-hand-v1': [
    {
      key: 'blooded-edge-t1',
      name: 'Krwawa krawędź',
      kind: 'PREFIX',
      tier: 1,
      weight: 100,
      tags: ['martial', 'offense', 'strength'],
      incompatibleTags: ['arcane'],
      classTags: ['WARRIOR'],
      minimumPowerLevel: 1,
      minimumRoll: 1,
      maximumRoll: 3,
      powerCost: 2,
      stat: 'strength',
    },
    {
      key: 'executioners-balance-t1',
      name: 'Równowaga kata',
      kind: 'PREFIX',
      tier: 1,
      weight: 65,
      tags: ['martial', 'precision', 'agility'],
      incompatibleTags: ['bulwark'],
      minimumPowerLevel: 4,
      minimumRoll: 1,
      maximumRoll: 2,
      powerCost: 2,
      stat: 'agility',
    },
    {
      key: 'warded-grip-t1',
      name: 'Chroniona rękojeść',
      kind: 'SUFFIX',
      tier: 1,
      weight: 90,
      tags: ['martial', 'defense', 'bulwark'],
      incompatibleTags: ['precision'],
      minimumPowerLevel: 1,
      minimumRoll: 1,
      maximumRoll: 2,
      powerCost: 2,
      stat: 'armor',
    },
    {
      key: 'unyielding-grip-t1',
      name: 'Nieustępliwy chwyt',
      kind: 'SUFFIX',
      tier: 1,
      weight: 70,
      tags: ['martial', 'resource'],
      incompatibleTags: [],
      minimumPowerLevel: 3,
      minimumRoll: 4,
      maximumRoll: 9,
      powerCost: 3,
      stat: 'maxHp',
    },
  ],
  'arcane-main-hand-v1': [
    {
      key: 'grave-insight-t1',
      name: 'Grobowe olśnienie',
      kind: 'PREFIX',
      tier: 1,
      weight: 100,
      tags: ['arcane', 'offense', 'intelligence'],
      incompatibleTags: ['martial'],
      classTags: ['MAGE'],
      minimumPowerLevel: 1,
      minimumRoll: 1,
      maximumRoll: 3,
      powerCost: 2,
      stat: 'intelligence',
    },
    {
      key: 'hollow-reservoir-t1',
      name: 'Pusty rezerwuar',
      kind: 'SUFFIX',
      tier: 1,
      weight: 85,
      tags: ['arcane', 'resource'],
      incompatibleTags: [],
      classTags: ['MAGE'],
      minimumPowerLevel: 1,
      minimumRoll: 5,
      maximumRoll: 12,
      powerCost: 3,
      stat: 'maxEnergy',
    },
    {
      key: 'bone-ward-t1',
      name: 'Kościana osłona',
      kind: 'SUFFIX',
      tier: 1,
      weight: 55,
      tags: ['arcane', 'defense'],
      incompatibleTags: [],
      minimumPowerLevel: 4,
      minimumRoll: 1,
      maximumRoll: 2,
      powerCost: 2,
      stat: 'armor',
    },
  ],
  'ranger-main-hand-v1': [
    {
      key: 'predators-tension-t1',
      name: 'Napięcie drapieżcy',
      kind: 'PREFIX',
      tier: 1,
      weight: 100,
      tags: ['ranger', 'offense', 'agility'],
      incompatibleTags: ['bulwark'],
      classTags: ['ARCHER'],
      minimumPowerLevel: 1,
      minimumRoll: 1,
      maximumRoll: 3,
      powerCost: 2,
      stat: 'agility',
    },
    {
      key: 'patient-string-t1',
      name: 'Cierpliwa cięciwa',
      kind: 'SUFFIX',
      tier: 1,
      weight: 80,
      tags: ['ranger', 'resource'],
      incompatibleTags: [],
      minimumPowerLevel: 1,
      minimumRoll: 4,
      maximumRoll: 10,
      powerCost: 3,
      stat: 'maxEnergy',
    },
    {
      key: 'thorn-wrapped-t1',
      name: 'Opleciony cierniem',
      kind: 'SUFFIX',
      tier: 1,
      weight: 60,
      tags: ['ranger', 'defense', 'bulwark'],
      incompatibleTags: ['predator'],
      minimumPowerLevel: 4,
      minimumRoll: 1,
      maximumRoll: 2,
      powerCost: 2,
      stat: 'armor',
    },
  ],
  'defender-off-hand-v1': [
    {
      key: 'chitin-plated-t1',
      name: 'Chitynowe poszycie',
      kind: 'PREFIX',
      tier: 1,
      weight: 100,
      tags: ['defense', 'bulwark', 'chitin'],
      incompatibleTags: ['precision'],
      minimumPowerLevel: 5,
      minimumRoll: 2,
      maximumRoll: 4,
      powerCost: 3,
      stat: 'armor',
    },
    {
      key: 'survivors-binding-t1',
      name: 'Wiązanie ocalałego',
      kind: 'SUFFIX',
      tier: 1,
      weight: 90,
      tags: ['defense', 'vitality'],
      incompatibleTags: [],
      minimumPowerLevel: 5,
      minimumRoll: 8,
      maximumRoll: 16,
      powerCost: 3,
      stat: 'maxHp',
    },
  ],
};

export const ITEM_RELICS: Readonly<Record<string, ItemRelicEffectDefinition>> = {
  'ashen-lens-v1': {
    key: 'ashen-lens-v1',
    name: 'Soczewka Popielnego Widzenia',
    description:
      'Arcane Spark rozszczepia się i trafia wszystkich żywych przeciwników, lecz każdy pocisk zadaje 82% normalnych obrażeń.',
    skillKey: 'mage-arcane-spark',
    modifier: {
      version: 1,
      type: 'SET_TARGETING',
      targeting: 'ALL_ENEMIES',
      coefficientMultiplier: 0.82,
    },
    powerCost: 4,
    uniqueGroup: 'skill-targeting',
  },
  'executioners-hook-v1': {
    key: 'executioners-hook-v1',
    name: 'Hak Egzekutora',
    description: 'Execution kosztuje o 5 energii mniej, ale nie może kosztować mniej niż 10.',
    skillKey: 'warrior-execution',
    modifier: { version: 1, type: 'ADJUST_ENERGY_COST', flatDelta: -5, minimum: 10 },
    powerCost: 3,
    uniqueGroup: 'skill-cost',
  },
};

export const ITEM_CURSES: Readonly<Record<string, ItemCurseDefinition>> = {
  'hollow-shell-v1': {
    key: 'hollow-shell-v1',
    name: 'Klątwa Wydrążonej Skorupy',
    description: 'Moc reliktu wysysa odporność noszącego.',
    preview: 'Po założeniu: -2 pancerza. Koszt pozostaje aktywny tak długo, jak przedmiot jest założony.',
    cost: { type: 'STAT_PENALTY', statBonuses: { armor: -2 } },
    powerCredit: 2,
  },
  'starved-veins-v1': {
    key: 'starved-veins-v1',
    name: 'Klątwa Głodnych Żył',
    description: 'Przedmiot ogranicza działanie leczenia otrzymywanego w walce.',
    preview: 'Po założeniu otrzymywane leczenie w walce jest zmniejszone o 20%.',
    cost: { type: 'HEALING_RECEIVED_MULTIPLIER', multiplier: 0.8 },
    powerCredit: 3,
  },
};

export const ITEM_SALVAGE_PROFILES: Readonly<Record<string, ItemSalvageProfile>> = {
  'starter-weapon-v1': {
    key: 'starter-weapon-v1',
    version: 1,
    deterministic: [{ itemKey: 'rabbit-fur', quantity: 2 }],
  },
  'chitin-buckler-v1': {
    key: 'chitin-buckler-v1',
    version: 1,
    deterministic: [{ itemKey: 'scorpion-chitin', quantity: 4 }],
    rare: {
      itemKey: 'scorpion-stinger',
      chance: 0.2,
      pityKey: 'salvage:chitin-buckler:stinger:v1',
      guaranteedAfterMisses: 4,
    },
  },
  'ashen-focus-v1': {
    key: 'ashen-focus-v1',
    version: 1,
    deterministic: [
      { itemKey: 'scorpion-chitin', quantity: 2 },
      { itemKey: 'venom-sac', quantity: 1 },
    ],
    rare: {
      itemKey: 'rabbit-foot',
      chance: 0.15,
      pityKey: 'salvage:ashen-focus:rabbit-foot:v1',
      guaranteedAfterMisses: 5,
    },
  },
  'executioners-hookblade-v1': {
    key: 'executioners-hookblade-v1',
    version: 1,
    deterministic: [
      { itemKey: 'scorpion-chitin', quantity: 4 },
      { itemKey: 'scorpion-stinger', quantity: 2 },
      { itemKey: 'venom-sac', quantity: 1 },
    ],
    rare: {
      itemKey: 'rabbit-foot',
      chance: 0.2,
      pityKey: 'salvage:executioners-hookblade:rabbit-foot:v1',
      guaranteedAfterMisses: 4,
    },
  },
};

export const ITEM_RECIPES: Readonly<Record<string, ItemRecipeDefinition>> = {
  'tempered-chitin-buckler-v1': {
    key: 'tempered-chitin-buckler-v1',
    version: 1,
    name: 'Hartowany puklerz chitynowy',
    outputItemKey: 'tempered-chitin-buckler',
    outputQuantity: 1,
    silverCost: 140,
    inputs: [
      { itemKey: 'scorpion-chitin', quantity: 8 },
      { itemKey: 'rabbit-fur', quantity: 3 },
    ],
    requiredLevel: 5,
    workstationKey: 'quartermaster-forge',
    regionKey: 'greenfields',
    specializationCost: 1,
    deterministicSeedSalt: 'recipe:tempered-chitin-buckler:v1',
  },
  'ashen-reliquary-focus-v1': {
    key: 'ashen-reliquary-focus-v1',
    version: 1,
    name: 'Popielne ognisko relikwiarza',
    outputItemKey: 'ashen-reliquary-focus',
    outputQuantity: 1,
    silverCost: 360,
    inputs: [
      { itemKey: 'venom-sac', quantity: 2 },
      { itemKey: 'scorpion-stinger', quantity: 3 },
      { itemKey: 'rabbit-foot', quantity: 2 },
    ],
    requiredLevel: 10,
    workstationKey: 'quartermaster-forge',
    regionKey: 'greenfields',
    specializationCost: 2,
    deterministicSeedSalt: 'recipe:ashen-reliquary-focus:v1',
  },
  'executioners-hookblade-v1': {
    key: 'executioners-hookblade-v1',
    version: 1,
    name: 'Hakowe ostrze Egzekutora',
    outputItemKey: 'executioners-hookblade',
    outputQuantity: 1,
    silverCost: 900,
    inputs: [
      { itemKey: 'scorpion-stinger', quantity: 6 },
      { itemKey: 'venom-sac', quantity: 4 },
      { itemKey: 'rabbit-foot', quantity: 2 },
    ],
    requiredLevel: 40,
    workstationKey: 'quartermaster-forge',
    regionKey: 'greenfields',
    specializationCost: 3,
    deterministicSeedSalt: 'recipe:executioners-hookblade:v1',
  },
};
