import { useEffect, useMemo, useState } from 'react';
import type { InventoryItemPayload, TradeParticipantPayload, TradeSnapshot } from '../../contracts/socket';
import { useGameConnection } from '../../game/realtime/GameConnectionProvider';
import { useGameState } from '../../game/state/gameStore';
import { useI18n } from '../../i18n/I18nProvider';
import { Modal } from '../modals/Modal';

interface Props { trade: TradeSnapshot; onChange: (trade: TradeSnapshot) => void; onClose: () => void; }
const terminal = (status: TradeSnapshot['status']) => ['COMPLETED', 'CANCELLED', 'EXPIRED'].includes(status);
function Offer({ participant, own }: { participant: TradeParticipantPayload; own: boolean }): React.JSX.Element {
  return <section className={`rounded border p-4 ${participant.accepted ? 'border-emerald-400/50 bg-emerald-950/20' : 'border-amber-400/20 bg-black/20'}`}><div className="flex items-center justify-between gap-3"><h3 className="font-display text-lg text-amber-100">{participant.name}{own ? ' (Ty)' : ''}</h3><span className={participant.accepted ? 'text-xs text-emerald-300' : 'text-xs text-slate-400'}>{participant.accepted ? '✓ Zaakceptowano' : 'Oczekuje'}</span></div><p className="mt-2 text-sm text-amber-200">Srebro: {participant.silver}</p><div className="mt-3 space-y-2">{participant.items.length === 0 ? <p className="text-xs text-slate-500">Brak przedmiotów.</p> : null}{participant.items.map((item) => <div key={item.inventoryItemId} className="flex items-center gap-2 rounded border border-white/10 bg-slate-950/35 p-2"><span className="text-xl">{item.icon}</span><div><strong className="block text-sm">{item.name}</strong><span className="text-xs text-slate-400">Ilość: {item.quantity}</span></div></div>)}</div></section>;
}

export function TradeModal({ trade, onChange, onClose }: Props): React.JSX.Element {
  const connection = useGameConnection(); const state = useGameState(); const { locale } = useI18n(); const [busy, setBusy] = useState(false);
  const selfId = state.self?.characterId; const own = trade.initiator.characterId === selfId ? trade.initiator : trade.recipient; const other = trade.initiator.characterId === selfId ? trade.recipient : trade.initiator; const isRecipient = trade.recipient.characterId === selfId;
  const [silver, setSilver] = useState(String(own.silver)); const offered = useMemo(() => new Map(own.items.map((item) => [item.inventoryItemId, item.quantity])), [own.items]); const [quantities, setQuantities] = useState<Record<string, string>>({});
  useEffect(() => { setSilver(String(own.silver)); setQuantities(Object.fromEntries(trade.inventory.items.map((item) => [item.id, String(offered.get(item.id) ?? 0)]))); }, [own.silver, offered, trade.inventory.items]);
  const mutate = async (operation: () => Promise<TradeSnapshot>) => { if (busy) return; setBusy(true); try { onChange(await operation()); } catch { /* global socket notification */ } finally { setBusy(false); } };
  const saveItem = (item: InventoryItemPayload) => { const value = Number(quantities[item.id] ?? 0); if (Number.isInteger(value) && value >= 0 && value <= item.quantity) void mutate(() => connection.setTradeItem(trade.tradeId, item.id, value)); };
  const saveSilver = () => { const value = Number(silver); if (Number.isInteger(value) && value >= 0 && value <= trade.inventory.silver) void mutate(() => connection.setTradeSilver(trade.tradeId, value)); };

  if (trade.status === 'REQUESTED') return <Modal title={locale === 'pl' ? 'Prośba o handel' : 'Trade request'} subtitle={`${trade.initiator.name} → ${trade.recipient.name}`} icon="↔" onClose={onClose} widthClass="max-w-md"><p className="text-sm text-slate-300">{isRecipient ? `${trade.initiator.name} chce z Tobą handlować.` : `Oczekiwanie na ${trade.recipient.name}.`}</p><div className="mt-5 flex justify-end gap-2">{isRecipient ? <><button className="hud-utility-button" disabled={busy} onClick={() => void mutate(() => connection.respondTrade(trade.tradeId, false))}>Odrzuć</button><button className="hud-utility-button" disabled={busy} onClick={() => void mutate(() => connection.respondTrade(trade.tradeId, true))}>Akceptuj</button></> : <button className="hud-utility-button" onClick={onClose}>Anuluj prośbę</button>}</div></Modal>;
  if (terminal(trade.status)) return <Modal title="Handel" icon="↔" onClose={onClose} widthClass="max-w-md"><p className="text-center text-sm">{trade.status === 'COMPLETED' ? 'Handel zakończony pomyślnie.' : trade.status === 'EXPIRED' ? 'Handel wygasł.' : 'Handel anulowany.'}</p></Modal>;

  return <Modal title={`Handel z ${other.name}`} subtitle="Każda zmiana oferty cofa obie akceptacje." icon="↔" onClose={onClose} widthClass="max-w-6xl"><div className="grid gap-4 lg:grid-cols-2"><Offer participant={own} own /><Offer participant={other} own={false} /></div><div className="mt-5 grid gap-4 lg:grid-cols-[minmax(0,1fr)_260px]"><section className="rounded border border-white/10 bg-black/20 p-4"><h3 className="modal-section-title">Twoje przedmioty</h3><div className="mt-3 max-h-72 space-y-2 overflow-auto">{trade.inventory.items.map((item) => <div key={item.id} className="flex items-center gap-3 rounded border border-white/10 bg-slate-950/35 p-2"><span>{item.icon}</span><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{item.name}</strong><span className="text-xs text-slate-400">Dostępne: {item.quantity}{item.equippedSlot ? ' · założony' : ''}</span></div><input className="w-20 rounded bg-slate-950 px-2 py-1 text-right" type="number" min={0} max={item.quantity} disabled={busy || Boolean(item.equippedSlot)} value={quantities[item.id] ?? '0'} onChange={(event) => setQuantities((current) => ({ ...current, [item.id]: event.target.value }))}/><button className="hud-utility-button" disabled={busy || Boolean(item.equippedSlot)} onClick={() => saveItem(item)}>Ustaw</button></div>)}</div></section><section className="rounded border border-amber-400/20 bg-black/20 p-4"><h3 className="modal-section-title">Srebro</h3><p className="mt-2 text-xs text-slate-400">Masz {trade.inventory.silver} srebra. Złoto nie jest obsługiwane.</p><input className="mt-3 w-full rounded bg-slate-950 px-3 py-2 text-right" type="number" min={0} max={trade.inventory.silver} value={silver} disabled={busy} onChange={(event) => setSilver(event.target.value)}/><button className="hud-utility-button mt-2 w-full" disabled={busy} onClick={saveSilver}>Ustaw srebro</button></section></div><div className="mt-5 flex justify-end gap-2"><button className="hud-utility-button" disabled={busy} onClick={onClose}>Anuluj handel</button><button className="hud-utility-button" disabled={busy || own.accepted || trade.status === 'LOCKED'} onClick={() => void mutate(() => connection.acceptTrade(trade.tradeId))}>{own.accepted ? 'Zaakceptowano' : 'Akceptuj ofertę'}</button></div></Modal>;
}
