import { useState } from 'react';
import { useGameConnection } from '../../game/realtime/GameConnectionProvider';
import { useSocialState } from '../../game/state/socialStore';

export function RecentTab({ busy, pl, run }: { busy: boolean; pl: boolean; run: (op: () => Promise<unknown>) => Promise<void> }): React.JSX.Element {
  const connection = useGameConnection();
  const social = useSocialState();
  const [mentorActive, setMentorActive] = useState(social.mentorProfile?.active ?? false);
  return <div className="grid gap-5 lg:grid-cols-2">
    <section className="rounded-xl border border-white/10 bg-slate-950/45 p-4"><p className="eyebrow">{pl ? 'Ostatni współgracze' : 'Recent players'}</p><div className="mt-3 space-y-2">{social.recentPlayers.length === 0 ? <p className="text-sm text-slate-500">{pl ? 'Historia pojawi się po aktywnościach.' : 'History appears after activities.'}</p> : social.recentPlayers.map((player) => <article key={`${player.characterId}:${player.completedAt}`} className="rounded border border-white/10 bg-white/[0.03] p-3"><div className="flex items-center justify-between"><div><strong className="text-amber-50">{player.name}</strong><p className="text-xs text-slate-500">{player.activityKey} · {player.outcome}</p></div><span className={player.finished && !player.disconnected ? 'text-emerald-300' : 'text-amber-300'}>{player.finished ? '✓' : '!'}</span></div><div className="mt-2 flex gap-2"><button disabled={busy} onClick={() => void run(() => connection.addSocialContact(player.characterId))} className="rounded border border-emerald-300/25 px-2 py-1 text-[10px] text-emerald-200">{pl ? 'Kontakt' : 'Contact'}</button><button disabled={busy} onClick={() => void run(() => connection.setSocialBlock(player.characterId, true))} className="rounded border border-rose-300/25 px-2 py-1 text-[10px] text-rose-200">{pl ? 'Blokuj' : 'Block'}</button></div></article>)}</div></section>
    <section className="rounded-xl border border-amber-300/20 bg-slate-950/45 p-4"><p className="eyebrow">{pl ? 'Mentoring' : 'Mentoring'}</p><p className="mt-2 text-sm leading-6 text-slate-300">{pl ? 'Nagrody są użytkowe i kosmetyczne. Ten sam użytkownik, AFK oraz przekroczenie limitu tygodniowego nie kwalifikują nagrody.' : 'Rewards are utility/cosmetic. Same-account, AFK and weekly-cap abuse are rejected.'}</p><div className="mt-4 flex items-center justify-between rounded border border-white/10 p-3"><div><strong className="text-amber-100">{pl ? 'Profil mentora' : 'Mentor profile'}</strong><p className="text-xs text-slate-500">Rep. {social.mentorProfile?.reputation ?? 0} · {social.mentorProfile?.weeklyCompleted ?? 0}/5</p></div><button disabled={busy} onClick={() => { const next = !mentorActive; setMentorActive(next); void run(() => connection.setMentorProfile({ active: next, language: pl ? 'pl' : 'en', activityKeys: ['expedition:ashen-pilgrimage', 'region:ashen-march'] })); }} className={`rounded border px-3 py-1.5 text-xs ${mentorActive ? 'border-emerald-300/30 text-emerald-200' : 'border-white/15 text-slate-300'}`}>{mentorActive ? (pl ? 'Aktywny' : 'Active') : (pl ? 'Nieaktywny' : 'Inactive')}</button></div></section>
  </div>;
}

