import { useGameConnection } from '../../game/realtime/GameConnectionProvider';
import { useSocialState } from '../../game/state/socialStore';

export function GuildTab({ busy, pl, run }: { busy: boolean; pl: boolean; run: (op: () => Promise<unknown>) => Promise<void> }): React.JSX.Element {
  const connection = useGameConnection();
  const social = useSocialState();
  const guild = social.guild;
  const canContract = guild?.permissions.includes('CONTRACT_MANAGE');
  const canProject = guild?.permissions.includes('PROJECT_MANAGE');
  if (!guild) return <p className="py-12 text-center text-sm text-slate-500">{pl ? 'Dołącz do gildii, aby korzystać z kontraktów, projektów i banku.' : 'Join a guild to use contracts, projects and the bank.'}</p>;
  return <div className="space-y-5">
    <header className="grid gap-3 rounded-xl border border-amber-300/20 bg-amber-950/10 p-4 sm:grid-cols-3"><div><p className="eyebrow">{pl ? 'Poziom gildii' : 'Guild level'}</p><strong className="text-2xl text-amber-100">{guild.level}</strong></div><div><p className="eyebrow">XP</p><strong className="text-2xl text-amber-100">{guild.experience}</strong></div><div><p className="eyebrow">{pl ? 'Odblokowania' : 'Unlocks'}</p><strong className="text-sm text-amber-100">{guild.unlockKeys.length ? guild.unlockKeys.join(', ') : '—'}</strong></div></header>
    <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-white/10 bg-slate-950/45 p-4"><div className="flex items-center justify-between"><p className="eyebrow">{pl ? 'Kontrakty' : 'Contracts'}</p>{canContract ? <button disabled={busy} onClick={() => void run(() => connection.createGuildContract('ashen-ward'))} className="rounded border border-amber-300/25 px-2 py-1 text-[10px] text-amber-200">+</button> : null}</div><div className="mt-3 space-y-2">{guild.contracts.map((contract) => { const progress = contract.contributions.filter((entry) => entry.qualified && !entry.afk).reduce((sum, entry) => sum + entry.amount, 0); return <article key={contract.id} className="rounded border border-white/10 p-3"><strong className="text-amber-50">{contract.snapshot.title}</strong><p className="text-xs text-slate-500">v{contract.definitionVersion} · {Math.min(progress, contract.snapshot.target)}/{contract.snapshot.target} · {contract.status}</p>{canContract && contract.status === 'COMPLETED' ? <button disabled={busy} onClick={() => void run(() => connection.settleGuildContract(contract.id))} className="mt-2 rounded border border-emerald-300/25 px-2 py-1 text-[10px] text-emerald-200">{pl ? 'Rozlicz' : 'Settle'}</button> : null}</article>; })}</div></section>
    <section className="rounded-xl border border-white/10 bg-slate-950/45 p-4"><div className="flex items-center justify-between"><p className="eyebrow">{pl ? 'Projekt gildii' : 'Guild project'}</p>{canProject && !guild.projects.some((project) => project.status === 'ACTIVE') ? <button disabled={busy} onClick={() => void run(() => connection.createGuildProject('ritual-hall'))} className="rounded border border-amber-300/25 px-2 py-1 text-[10px] text-amber-200">+</button> : null}</div><div className="mt-3 space-y-2">{guild.projects.map((project) => <article key={project.id} className="rounded border border-white/10 p-3"><strong className="text-amber-50">{project.snapshot.title}</strong><p className="text-xs text-slate-500">v{project.definitionVersion} · {pl ? 'etap' : 'stage'} {Math.min(project.stageIndex + 1, project.snapshot.stages.length)}/{project.snapshot.stages.length} · {project.stageProgress} · {project.status}</p>{canProject && project.status === 'COMPLETED' ? <button disabled={busy} onClick={() => void run(() => connection.settleGuildProject(project.id))} className="mt-2 rounded border border-emerald-300/25 px-2 py-1 text-[10px] text-emerald-200">{pl ? 'Rozlicz' : 'Settle'}</button> : null}</article>)}</div></section></div>
    <section className="rounded-xl border border-white/10 bg-slate-950/45 p-4"><p className="eyebrow">{pl ? 'Bank gildii' : 'Guild bank'}</p><p className="mt-1 text-xs text-slate-500">{pl ? 'Srebro i premium gold nie są obsługiwane. Wypłaty mają blokady transakcyjne, limity dzienne i niezmienny audyt.' : 'Silver and premium gold are unsupported. Withdrawals use transaction locks, daily limits and immutable audit.'}</p><div className="mt-3 grid gap-2 md:grid-cols-2">{guild.bank.map((item) => <article key={item.id} className="flex items-center justify-between rounded border border-white/10 p-3"><div><strong className="text-amber-50">{item.itemName}</strong><p className="text-xs text-slate-500">{item.tabKey} · x{item.quantity}{item.lockedProjectKey ? ` · LOCK ${item.lockedProjectKey}` : ''}</p></div>{guild.permissions.includes('BANK_WITHDRAW') && !item.lockedProjectKey ? <button disabled={busy} onClick={() => void run(() => connection.withdrawGuildBank(item.id, 1))} className="rounded border border-emerald-300/25 px-2 py-1 text-[10px] text-emerald-200">−1</button> : null}</article>)}</div></section>
    <section className="rounded-xl border border-white/10 bg-slate-950/45 p-4"><p className="eyebrow">{pl ? 'Kalendarz' : 'Calendar'}</p><div className="mt-3 space-y-2">{guild.events.map((event) => <article key={event.id} className="flex flex-wrap items-center justify-between gap-2 rounded border border-white/10 p-3"><div><strong className="text-amber-50">{event.title}</strong><p className="text-xs text-slate-500">{new Date(event.startsAt).toLocaleString()} · {event.durationMinutes} min</p></div><div className="flex gap-1">{(['YES', 'MAYBE', 'NO'] as const).map((response) => <button key={response} disabled={busy} onClick={() => void run(() => connection.rsvpGuildEvent(event.id, response))} className="rounded border border-white/15 px-2 py-1 text-[9px] text-slate-300">{response}</button>)}</div></article>)}</div></section>
  </div>;
}

