import type { CharacterClass } from '../../common/domain/game.types.js';
import type { SkillCatalogDefinition } from './skill.types.js';

type BranchSkillInput = Omit<
  SkillCatalogDefinition,
  'characterClass' | 'displayOrder' | 'treeRow' | 'treeColumn' | 'maxRank'
>;

const visual = (
  animationKey: string,
  accentColor: string,
  projectileEffectKey?: string,
): Pick<SkillCatalogDefinition, 'animationKey' | 'visual'> => ({
  animationKey,
  visual: {
    castEffectKey: `${animationKey}:cast`,
    projectileEffectKey,
    impactEffectKey: `${animationKey}:impact`,
    accentColor,
    travelMs: projectileEffectKey ? 420 : undefined,
  },
});

const buildTree = (
  characterClass: CharacterClass,
  skills: readonly BranchSkillInput[],
): readonly SkillCatalogDefinition[] => {
  const positions = [
    { treeRow: 0, treeColumn: 0 },
    { treeRow: 1, treeColumn: -1 },
    { treeRow: 1, treeColumn: 1 },
    { treeRow: 2, treeColumn: -1 },
    { treeRow: 2, treeColumn: 1 },
    { treeRow: 3, treeColumn: -1 },
    { treeRow: 3, treeColumn: 1 },
    { treeRow: 4, treeColumn: 0 },
  ] as const;

  return skills.map((skill, index) => ({
    ...skill,
    characterClass,
    displayOrder: index + 1,
    maxRank: 1,
    ...positions[index]!,
  }));
};

const mage = buildTree('MAGE', [
  {
    key: 'mage-arcane-spark',
    name: 'Arcane Spark',
    description: 'Launches a fast arcane bolt at one enemy.',
    minimumLevel: 10,
    energyCost: 10,
    cooldownTurns: 0,
    targeting: 'ENEMY',
    icon: '✦',
    prerequisiteKeys: [],
    effects: [{ type: 'DAMAGE', scaling: 'INTELLIGENCE', coefficient: 1, damageType: 'ARCANE' }],
    ...visual('mage-arcane-spark', '#c4b5fd', 'vfx:arcane-bolt'),
  },
  {
    key: 'mage-flame-orb',
    name: 'Flame Orb',
    description: 'Hurls a burning orb that ignites its target.',
    minimumLevel: 20,
    energyCost: 18,
    cooldownTurns: 1,
    targeting: 'ENEMY',
    icon: '●',
    prerequisiteKeys: ['mage-arcane-spark'],
    effects: [
      { type: 'DAMAGE', scaling: 'INTELLIGENCE', coefficient: 1.35, damageType: 'FIRE' },
      { type: 'APPLY_STATUS', statusKey: 'BURN', durationTurns: 2, magnitude: 0.25 },
    ],
    ...visual('mage-flame-orb', '#fb923c', 'vfx:flame-orb'),
  },
  {
    key: 'mage-frost-nova',
    name: 'Frost Nova',
    description: 'Freezes the battlefield, damaging and slowing every enemy.',
    minimumLevel: 20,
    energyCost: 20,
    cooldownTurns: 2,
    targeting: 'AREA',
    icon: '❄',
    prerequisiteKeys: ['mage-arcane-spark'],
    effects: [
      { type: 'DAMAGE', scaling: 'INTELLIGENCE', coefficient: 0.75, damageType: 'FROST' },
      { type: 'APPLY_STATUS', statusKey: 'SLOWED', durationTurns: 2, magnitude: 0.25 },
    ],
    ...visual('mage-frost-nova', '#7dd3fc'),
  },
  {
    key: 'mage-ember-lance',
    name: 'Ember Lance',
    description: 'Pierces one enemy with concentrated fire that ignores part of its armor.',
    minimumLevel: 30,
    energyCost: 26,
    cooldownTurns: 2,
    targeting: 'ENEMY',
    icon: '↗',
    prerequisiteKeys: ['mage-flame-orb'],
    effects: [
      {
        type: 'DAMAGE',
        scaling: 'INTELLIGENCE',
        coefficient: 1.9,
        damageType: 'FIRE',
        armorPenetration: 0.2,
      },
    ],
    ...visual('mage-ember-lance', '#f97316', 'vfx:ember-lance'),
  },
  {
    key: 'mage-ice-barrier',
    name: 'Ice Barrier',
    description: 'Surrounds the caster with a temporary shield of enchanted ice.',
    minimumLevel: 30,
    energyCost: 24,
    cooldownTurns: 3,
    targeting: 'SELF',
    icon: '◇',
    prerequisiteKeys: ['mage-frost-nova'],
    effects: [{ type: 'SHIELD', scaling: 'INTELLIGENCE', coefficient: 1.6, durationTurns: 2 }],
    ...visual('mage-ice-barrier', '#bae6fd'),
  },
  {
    key: 'mage-meteor',
    name: 'Meteor',
    description: 'Calls down a meteor that burns every enemy.',
    minimumLevel: 40,
    energyCost: 38,
    cooldownTurns: 3,
    targeting: 'AREA',
    icon: '☄',
    prerequisiteKeys: ['mage-ember-lance'],
    effects: [
      { type: 'DAMAGE', scaling: 'INTELLIGENCE', coefficient: 1.8, damageType: 'FIRE' },
      { type: 'APPLY_STATUS', statusKey: 'BURN', durationTurns: 2, magnitude: 0.35 },
    ],
    ...visual('mage-meteor', '#ef4444'),
  },
  {
    key: 'mage-time-lock',
    name: 'Time Lock',
    description: 'Suspends one enemy in time and prevents its next action.',
    minimumLevel: 40,
    energyCost: 34,
    cooldownTurns: 4,
    targeting: 'ENEMY',
    icon: '◴',
    prerequisiteKeys: ['mage-ice-barrier'],
    effects: [{ type: 'APPLY_STATUS', statusKey: 'STUNNED', durationTurns: 1 }],
    ...visual('mage-time-lock', '#a5b4fc', 'vfx:time-rift'),
  },
  {
    key: 'mage-elemental-cataclysm',
    name: 'Elemental Cataclysm',
    description: 'Combines fire, frost, and arcane force in a devastating battlefield spell.',
    minimumLevel: 50,
    energyCost: 55,
    cooldownTurns: 5,
    targeting: 'AREA',
    icon: '✺',
    prerequisiteKeys: ['mage-meteor', 'mage-time-lock'],
    effects: [
      { type: 'DAMAGE', scaling: 'INTELLIGENCE', coefficient: 2.6, damageType: 'ARCANE' },
      { type: 'APPLY_STATUS', statusKey: 'BURN', durationTurns: 2, magnitude: 0.3 },
      { type: 'APPLY_STATUS', statusKey: 'SLOWED', durationTurns: 2, magnitude: 0.3 },
    ],
    ...visual('mage-elemental-cataclysm', '#d8b4fe'),
  },
]);

const warrior = buildTree('WARRIOR', [
  {
    key: 'warrior-shield-bash',
    name: 'Shield Bash',
    description: 'Strikes one enemy and briefly staggers it.',
    minimumLevel: 10,
    energyCost: 9,
    cooldownTurns: 1,
    targeting: 'ENEMY',
    icon: '◈',
    prerequisiteKeys: [],
    effects: [
      { type: 'DAMAGE', scaling: 'STRENGTH', coefficient: 1, damageType: 'PHYSICAL' },
      { type: 'APPLY_STATUS', statusKey: 'STUNNED', durationTurns: 1, chance: 0.35 },
    ],
    ...visual('warrior-shield-bash', '#fbbf24'),
  },
  {
    key: 'warrior-cleave',
    name: 'Cleave',
    description: 'Sweeps a weapon through every enemy.',
    minimumLevel: 20,
    energyCost: 16,
    cooldownTurns: 1,
    targeting: 'AREA',
    icon: '◒',
    prerequisiteKeys: ['warrior-shield-bash'],
    effects: [{ type: 'DAMAGE', scaling: 'STRENGTH', coefficient: 0.9, damageType: 'PHYSICAL' }],
    ...visual('warrior-cleave', '#f59e0b'),
  },
  {
    key: 'warrior-iron-guard',
    name: 'Iron Guard',
    description: 'Raises a defensive stance that greatly reduces incoming damage.',
    minimumLevel: 20,
    energyCost: 14,
    cooldownTurns: 2,
    targeting: 'SELF',
    icon: '⬟',
    prerequisiteKeys: ['warrior-shield-bash'],
    effects: [
      { type: 'APPLY_STATUS', statusKey: 'DAMAGE_REDUCTION', durationTurns: 2, magnitude: 0.45 },
    ],
    ...visual('warrior-iron-guard', '#d6d3d1'),
  },
  {
    key: 'warrior-whirlwind',
    name: 'Whirlwind',
    description: 'Spins through the enemy formation with a powerful series of strikes.',
    minimumLevel: 30,
    energyCost: 24,
    cooldownTurns: 2,
    targeting: 'AREA',
    icon: '↻',
    prerequisiteKeys: ['warrior-cleave'],
    effects: [{ type: 'DAMAGE', scaling: 'STRENGTH', coefficient: 1.35, damageType: 'PHYSICAL' }],
    ...visual('warrior-whirlwind', '#fdba74'),
  },
  {
    key: 'warrior-battle-cry',
    name: 'Battle Cry',
    description: 'Increases the warrior’s damage and initiative for several turns.',
    minimumLevel: 30,
    energyCost: 20,
    cooldownTurns: 3,
    targeting: 'SELF',
    icon: '‼',
    prerequisiteKeys: ['warrior-iron-guard'],
    effects: [
      { type: 'APPLY_STATUS', statusKey: 'DAMAGE_INCREASE', durationTurns: 3, magnitude: 0.25 },
      { type: 'APPLY_STATUS', statusKey: 'HASTE', durationTurns: 3, magnitude: 0.2 },
    ],
    ...visual('warrior-battle-cry', '#fcd34d'),
  },
  {
    key: 'warrior-execution',
    name: 'Execution',
    description: 'Deals extreme damage to a badly wounded enemy.',
    minimumLevel: 40,
    energyCost: 30,
    cooldownTurns: 3,
    targeting: 'ENEMY',
    icon: '†',
    prerequisiteKeys: ['warrior-whirlwind'],
    effects: [
      {
        type: 'DAMAGE',
        scaling: 'STRENGTH',
        coefficient: 2.2,
        damageType: 'PHYSICAL',
        targetHpBelow: 0.3,
        bonusCoefficient: 0.8,
      },
    ],
    ...visual('warrior-execution', '#dc2626'),
  },
  {
    key: 'warrior-last-stand',
    name: 'Last Stand',
    description: 'Recovers health and hardens the warrior against incoming attacks.',
    minimumLevel: 40,
    energyCost: 28,
    cooldownTurns: 4,
    targeting: 'SELF',
    icon: '♜',
    prerequisiteKeys: ['warrior-battle-cry'],
    effects: [
      { type: 'HEAL', scaling: 'MAX_HP', coefficient: 0.3 },
      { type: 'APPLY_STATUS', statusKey: 'DAMAGE_REDUCTION', durationTurns: 2, magnitude: 0.35 },
    ],
    ...visual('warrior-last-stand', '#fef3c7'),
  },
  {
    key: 'warrior-unbreakable-assault',
    name: 'Unbreakable Assault',
    description: 'Charges through the enemy line with unstoppable force.',
    minimumLevel: 50,
    energyCost: 45,
    cooldownTurns: 5,
    targeting: 'AREA',
    icon: '♛',
    prerequisiteKeys: ['warrior-execution', 'warrior-last-stand'],
    effects: [
      { type: 'DAMAGE', scaling: 'STRENGTH', coefficient: 2.6, damageType: 'PHYSICAL' },
      { type: 'APPLY_STATUS', statusKey: 'STUNNED', durationTurns: 1, chance: 0.5 },
    ],
    ...visual('warrior-unbreakable-assault', '#facc15'),
  },
]);

const archer = buildTree('ARCHER', [
  {
    key: 'archer-quick-shot',
    name: 'Quick Shot',
    description: 'Fires a fast arrow at one enemy.',
    minimumLevel: 10,
    energyCost: 8,
    cooldownTurns: 0,
    targeting: 'ENEMY',
    icon: '➶',
    prerequisiteKeys: [],
    effects: [{ type: 'DAMAGE', scaling: 'AGILITY', coefficient: 1, damageType: 'PHYSICAL' }],
    ...visual('archer-quick-shot', '#bef264', 'vfx:arrow'),
  },
  {
    key: 'archer-piercing-arrow',
    name: 'Piercing Arrow',
    description: 'Fires an armor-piercing arrow at one enemy.',
    minimumLevel: 20,
    energyCost: 15,
    cooldownTurns: 1,
    targeting: 'ENEMY',
    icon: '➳',
    prerequisiteKeys: ['archer-quick-shot'],
    effects: [
      {
        type: 'DAMAGE',
        scaling: 'AGILITY',
        coefficient: 1.45,
        damageType: 'PHYSICAL',
        armorPenetration: 0.35,
      },
    ],
    ...visual('archer-piercing-arrow', '#a3e635', 'vfx:piercing-arrow'),
  },
  {
    key: 'archer-snare-trap',
    name: 'Snare Trap',
    description: 'Damages one enemy and prevents it from acting freely.',
    minimumLevel: 20,
    energyCost: 16,
    cooldownTurns: 2,
    targeting: 'ENEMY',
    icon: '⌘',
    prerequisiteKeys: ['archer-quick-shot'],
    effects: [
      { type: 'DAMAGE', scaling: 'AGILITY', coefficient: 0.65, damageType: 'PHYSICAL' },
      { type: 'APPLY_STATUS', statusKey: 'ROOTED', durationTurns: 2 },
    ],
    ...visual('archer-snare-trap', '#84cc16'),
  },
  {
    key: 'archer-volley',
    name: 'Volley',
    description: 'Rains arrows over every enemy.',
    minimumLevel: 30,
    energyCost: 22,
    cooldownTurns: 2,
    targeting: 'AREA',
    icon: '≋',
    prerequisiteKeys: ['archer-piercing-arrow'],
    effects: [{ type: 'DAMAGE', scaling: 'AGILITY', coefficient: 1, damageType: 'PHYSICAL' }],
    ...visual('archer-volley', '#d9f99d'),
  },
  {
    key: 'archer-evasive-roll',
    name: 'Evasive Roll',
    description: 'Avoids incoming attacks and gains initiative.',
    minimumLevel: 30,
    energyCost: 18,
    cooldownTurns: 3,
    targeting: 'SELF',
    icon: '⤾',
    prerequisiteKeys: ['archer-snare-trap'],
    effects: [
      { type: 'APPLY_STATUS', statusKey: 'DODGE', durationTurns: 1, magnitude: 0.6 },
      { type: 'APPLY_STATUS', statusKey: 'HASTE', durationTurns: 2, magnitude: 0.3 },
    ],
    ...visual('archer-evasive-roll', '#86efac'),
  },
  {
    key: 'archer-rain-of-arrows',
    name: 'Rain of Arrows',
    description: 'Blankets the battlefield with arrows that leave enemies bleeding.',
    minimumLevel: 40,
    energyCost: 32,
    cooldownTurns: 3,
    targeting: 'AREA',
    icon: '⇊',
    prerequisiteKeys: ['archer-volley'],
    effects: [
      { type: 'DAMAGE', scaling: 'AGILITY', coefficient: 1.65, damageType: 'PHYSICAL' },
      { type: 'APPLY_STATUS', statusKey: 'BLEED', durationTurns: 2, magnitude: 0.3 },
    ],
    ...visual('archer-rain-of-arrows', '#65a30d'),
  },
  {
    key: 'archer-predators-mark',
    name: 'Predator’s Mark',
    description: 'Marks one enemy, increasing all damage it receives.',
    minimumLevel: 40,
    energyCost: 25,
    cooldownTurns: 3,
    targeting: 'ENEMY',
    icon: '◎',
    prerequisiteKeys: ['archer-evasive-roll'],
    effects: [
      {
        type: 'APPLY_STATUS',
        statusKey: 'DAMAGE_TAKEN_INCREASE',
        durationTurns: 3,
        magnitude: 0.2,
      },
    ],
    ...visual('archer-predators-mark', '#f87171', 'vfx:hunter-mark'),
  },
  {
    key: 'archer-perfect-hunt',
    name: 'Perfect Hunt',
    description: 'Exploits every opening with a lethal, perfectly aimed shot.',
    minimumLevel: 50,
    energyCost: 45,
    cooldownTurns: 5,
    targeting: 'ENEMY',
    icon: '✧',
    prerequisiteKeys: ['archer-rain-of-arrows', 'archer-predators-mark'],
    effects: [
      {
        type: 'DAMAGE',
        scaling: 'AGILITY',
        coefficient: 3,
        damageType: 'PHYSICAL',
        armorPenetration: 0.4,
      },
    ],
    ...visual('archer-perfect-hunt', '#ecfccb', 'vfx:perfect-arrow'),
  },
]);

export const SKILL_CATALOG = [...mage, ...warrior, ...archer] as const;

export const skillsForClass = (characterClass: CharacterClass): readonly SkillCatalogDefinition[] =>
  SKILL_CATALOG.filter((skill) => skill.characterClass === characterClass);
